# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: example/proto/service.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class FooRequest(betterproto.Message):
    a: str = betterproto.string_field(1)


@dataclass
class FooResponse(betterproto.Message):
    pass


class FooServiceStub(betterproto.ServiceStub):
    async def foo(self, *, a: str = "") -> FooResponse:
        request = FooRequest()
        request.a = a

        return await self._unary_unary(
            "/example.FooService/Foo",
            request,
            FooResponse,
        )
